services:

  db:
    image: postgres:latest
    container_name: vaku
    restart: always
    volumes:
      - ./dataBase/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
    environment:
      - POSTGRES_DB=vaku
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminVaku
    ports:
      - "5432:5432"